### ISSUE TITLE
Staking Pool Investigation

### ISSUE THREAD

**Issue by MilGard91** [NexusMutual/smart-contracts#1152]

**Comment by rackstar** [comment]
## Affected Pools:
currently only pool 8 is affected by this bug

## Susceptible Pools:
but there are other pools that are susceptible (6, 9, 14, 15, 17, 21) because they have 0 shareSupply.

These susceptible pools will trigger the bug if they do any of the following:

depositTo
extendDeposit
withdraw
processExpiration
The FE released a temporary fix to block these operation on the susceptible pools to prevent them executing these actions before the smart-contract fix is released.
