### ISSUE TITLE
Implement 20% MCR limit on buy cover onchain

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#834]
Now that we track active cover amount onchain, we should restrict total active amount for any given product to 20% of the MCR value

**Comment by danoctavian** [comment]
Doesn't seem to be an easy way to restrict total active cover amount on-chain using active cover amount because we only track it *per asset* (ETH, DAI) and we don't track it per productId.

We'd need an aditional implementation for per product id, as far as i can tell

The current computation is useful but only for the MCR computation when evaluating total covered amount to compute Geared MCR.
