### ISSUE TITLE
Tokenomics: Add extra events

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#993]
These events are useful for Dune tracking

I have identified two places that we need some more events. These are in respect to the amount of eth injected and extracted by the RAMM, below I given a rough idea of what this might look like:

  ```
if (eth < TARGET_LIQUIDITY) {
      // inject eth
      uint timeLeftOnBudget = budget * LIQ_SPEED_PERIOD / FAST_LIQUIDITY_SPEED;
      uint maxToInject;
      uint injected;

      if (capital <= mcrValue + TARGET_LIQUIDITY) {
        maxToInject = 0;
      } else {
        maxToInject = Math.min(TARGET_LIQUIDITY - eth, capital - mcrValue - TARGET_LIQUIDITY);
      }

      if (elapsed <= timeLeftOnBudget) {
        injected = Math.min(elapsed * FAST_LIQUIDITY_SPEED / LIQ_SPEED_PERIOD, maxToInject);
      } else {
        uint injectedFast = timeLeftOnBudget * FAST_LIQUIDITY_SPEED / LIQ_SPEED_PERIOD;
        uint injectedSlow = (elapsed - timeLeftOnBudget) * LIQ_SPEED_B * 1 ether / LIQ_SPEED_PERIOD;
        injected = Math.min(maxToInject, injectedFast + injectedSlow);
      }

      **emit EthInjected(injected);**

      eth += injected;
      budget = budget > injected ? budget - injected : 0;

    } else {
      // extract eth
      uint extracted = Math.min(
        elapsed * LIQ_SPEED_A * 1 ether / LIQ_SPEED_PERIOD,
        eth - TARGET_LIQUIDITY // diff to target
      );
      eth -= extracted;

      **emit EthExtracted(extracted);**
   }
```

**Comment by rackstar** [comment]
`_getReserves` function is used in a few functions (both view and mutative):

#### Mutative:
* ramm.swapEthForNxm
* ramm.swapNxmForEth
* ramm.updateTwap (_getReserves is called here multiple times)
* ramm.getInternalPriceAndUpdateTwap (_getReserves is called here multiple times)

#### View:
* ramm.getReserves
* pool.getInternalTokenPriceInAsset -> ramm.getInternalPrice
* tokenController.getTokenPrice -> pool.getTokenPrice -> ramm.getSpotPrices

If our goal is to track the injected and extracted ETH amounts we should NOT emit these events on view functions and ONLY emit them on mutative functions.

Since`_getReserves` function can be called multiple times to calculate state values such as with `updateTwap`, we should also be careful that we emit these events ONLY once per function call (ideally right after when we store the new state - `storeState`).

**Comment by rackstar** [comment]
### Proposed solution:

The emit events needs to be outside of `_getReserves` function and it should be done right after `storeState`:

1. `_getReserves` function to return injected and extracted values along with the state
```solidity
function _getReserves(...) public view returns (State memory, uint injected, uint extracted) {
   ...
}
```
2. On the mutative functions after `storestate()` emit EthInjected/EthExtracted events
```solidity
(State memory state, uint injected, uint extracted) = _getReserves(...);

...

storeState(state);

if (injected > 0) {
  emit EthInjected(injected);
}
if (extracted > 0) {
  emit EthExtracted(extracted);
}

```

**Comment by rackstar** [comment]
@roxdanila @shark0der request for comments please for the above
